require 'rake'
require 'rake/testtask'

desc "Default Task"
task :default => [ :test ]

# Run the unit tests

Rake::TestTask.new { |t|
  t.libs << "test"
  t.pattern = 'test/**/*_test.rb'
  t.warning = true
}

namespace :test do
  task :isolated do
    ruby = File.join(*RbConfig::CONFIG.values_at('bindir', 'RUBY_INSTALL_NAME'))
    rdai_path = "#{File.dirname(__FILE__)}/../rdai/lib"
    Dir.glob("test/**/*_test.rb").all? do |file|
      system(ruby, '-w', "-Ilib:test:#{rdai_path}", file)
    end or raise "Failures"
  end
end